POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "NLW Summit 3",
  "details": "um evento para quem é apaixonado por programação",
  "maximumAttendees": 100,
  "slug": "nlw-summit-3"
}
